export enum Ranks {
  PRIVATE = "PRIVATE",
  CORPORAL = "CORPORAL",
  SERGEANT = "SERGEANT",
  MASETR_SERGEANT = "MASTER_SERGEANT",
  WARRANT_OFFICER = "WARRANT_OFFICER",
  LIUETENANT = "LIUETENANT",
  CAPTAIN = "CAPTAIN",
  MAJOR = "MAJOR",
  COLONEL = "COLONEL",
}

export enum SaveObjects {
  SOLDIERS = "SOLDIERS",
  COMPANY = "COMPANY",
  NAVIGATION = "NAVIGATION",
}

export enum SoldierJobs {
  RIFLEMAN = "RIFLEMAN",
  SQUAD_LEADER = "SQUAD_LEADER",
  SQUAD_GUNNER = "SQUAD_GUNNER",
  MG_CREW_GUNNER = "MG_CREW_GUNNER",
  MG_CREW_LOADER = "MG_CREW_LOADER",
  MG_CREWMAN = "MG_CREWMAN",
  MORTAR_TEAM_LEADER = "MORTAR_TEAM_LEADER",
  MORTAR_CREWMAN = "MORTAR_CREWMAN",
  SNIPER = "SNIPER",
  MEDIC = "MEDIC",
  SURGEON = "SURGEON",
  FIRE_TEAM_GUNNER = "FIRE_TEAM_GUNNER",
  FIRE_TEAM_RIFLEMAN = "FIRE_TEAM_RIFLEMAN",
  FIRE_TEAM_LEADER = "FIRE_TEAM_LEADER",
  PLATOON_LEADER = "PLATOON_LEADER",
  RECON_RIFLEMAN = "RECON_RIFLEMAN",
  PLATOON_COMMANDER = "PLATOON_COMMANDER",
  COMPANY_COMMANDER = "COMPANY_COMMANDER",
}

export enum SFSoldierJobs {
  SF_SQUAD_LEADER = "SF_SQUAD_LEADER",
  SF_SQUAD_GUNNER = "SF_SQUAD_GUNNER",
  SF_OPERATOR = "SF_OPERATOR",
  SF_DEMOLITIONIST = "SF_DEMOLITIONIST",
  SF_MARKSMAN = "SF_MARKSMAN",
}

export enum SupportTeamList {
  MG_TEAM = "MG_TEAM",
  MORTAR_TEAM = "MORTAR_TEAM",
  RECON_TEAM = "RECON_TEAM",
  MED_TEAM = "MED_TEAM",
  FIRE_TEAM = "FIRE_TEAM",
  COMMAND_TEAM = "COMMAND_TEAM",
  ASSAULT_SQUAD = "ASSAULT_SQUAD",
}
